// User configuration for the WSPR beacon.
//
// Do not edit this file to set up your own station. Instead copy
// include/config_local.h.example to include/config_local.h (gitignored) and
// define only the settings you want to change — the defaults below stay put, so
// `git pull` never conflicts with your station.
//
// WiFi credentials and the web/OTA passwords live in include/secrets.h (also gitignored).
// Out-of-range values stop the build (see the static_asserts in src/main.cpp).
#pragma once

#include <stdint.h>

#if __has_include("config_local.h")
#include "config_local.h"
#endif

// ---------------------------------------------------------------------------
// Defaults. Override any of these with a #define in config_local.h.
// ---------------------------------------------------------------------------

// ---------- station ----------
// CFG_CALLSIGN and CFG_LOCATOR have no default on purpose: transmitting with
// someone else's callsign is illegal, so the build stops until you set yours.
#if !defined(CFG_CALLSIGN) || !defined(CFG_LOCATOR)
#error "Copy include/config_local.h.example to include/config_local.h, then set CFG_CALLSIGN and CFG_LOCATOR to your own callsign and Maidenhead locator."
#endif

#ifndef CFG_POWER_DBM
#define CFG_POWER_DBM 20                   // reported power: 0..60, ending in 0, 3 or 7
#endif

// ---------- hardware ----------
#ifndef CFG_LED_PIN
#define CFG_LED_PIN 8                      // onboard LED on most C3 boards
#endif
#ifndef CFG_LED_ACTIVE_LOW
#define CFG_LED_ACTIVE_LOW true            // Super Mini LED is active-low
#endif
#ifndef CFG_SDA_PIN
#define CFG_SDA_PIN 21
#endif
#ifndef CFG_SCL_PIN
#define CFG_SCL_PIN 20
#endif

// ---------- Si5351 ----------
#ifndef CFG_XTAL_FREQ_HZ
#define CFG_XTAL_FREQ_HZ 25000000UL        // 25 MHz; some boards use 27 MHz
#endif
#ifndef CFG_XTAL_LOAD_PF
#define CFG_XTAL_LOAD_PF 8                 // 6, 8 or 10
#endif
#ifndef CFG_CORRECTION_PPB
#define CFG_CORRECTION_PPB 0               // per-board: calibrate yours, see README ('c' sets it at runtime)
#endif
#ifndef CFG_DRIVE_MA
#define CFG_DRIVE_MA 8                     // 2, 4, 6 or 8
#endif

// ---------- WSPR ----------
#ifndef CFG_CENTER_FREQ_HZ
#define CFG_CENTER_FREQ_HZ 14097100ULL     // middle of the 20m WSPR window (14.0970-14.0972 MHz)
#endif
#ifndef CFG_TX_RANDOM_OFFSET_HZ
#define CFG_TX_RANDOM_OFFSET_HZ 80         // random +/- per TX; up to 95 stays inside the 200 Hz window
#endif
#ifndef CFG_TX_EVERY_N_SLOTS
#define CFG_TX_EVERY_N_SLOTS 3             // 1..30; 3 = 1 TX per 6 min (~33%); Type 1 every 12 min with a 6-char locator
#endif
#ifndef CFG_NTP_SERVER
#define CFG_NTP_SERVER "pool.ntp.org"
#endif

// ---------- web interface ----------
#ifndef CFG_MDNS_NAME
#define CFG_MDNS_NAME "wspr"               // http://wspr.local/
#endif
#ifndef CFG_WEB_CHECK_HOST
#define CFG_WEB_CHECK_HOST true            // only answer to <name>, <name>.local or the IP (blocks DNS rebinding)
#endif

// ---------- console ----------
#ifndef CFG_SERIAL_BAUD
#define CFG_SERIAL_BAUD 115200
#endif
#ifndef CFG_STEP_HZ
#define CFG_STEP_HZ 10ULL                  // default step for + / -
#endif
#ifndef CFG_TONE_DWELL_MS
#define CFG_TONE_DWELL_MS 2000             // time per tone in the tone test
#endif
#ifndef CFG_LED_BLINK_MS
#define CFG_LED_BLINK_MS 250
#endif

// ---------------------------------------------------------------------------
// The values the firmware actually uses. Nothing to change below this line.
// ---------------------------------------------------------------------------

namespace config {

// ---------- station ----------
constexpr char CALLSIGN[] = CFG_CALLSIGN;
constexpr char LOCATOR[] = CFG_LOCATOR;             // 4- or 6-char Maidenhead locator (6 chars: alternates Type 1 / Type 3)
constexpr int8_t POWER_DBM = CFG_POWER_DBM;

// ---------- hardware ----------
constexpr int LED_PIN = CFG_LED_PIN;
constexpr bool LED_ACTIVE_LOW = CFG_LED_ACTIVE_LOW;
constexpr int SDA_PIN = CFG_SDA_PIN;
constexpr int SCL_PIN = CFG_SCL_PIN;

// ---------- Si5351 ----------
constexpr uint32_t XTAL_FREQ_HZ = CFG_XTAL_FREQ_HZ;
constexpr int XTAL_LOAD_PF = CFG_XTAL_LOAD_PF;
constexpr int32_t CORRECTION_PPB = CFG_CORRECTION_PPB;
constexpr int DRIVE_MA = CFG_DRIVE_MA;

// ---------- WSPR ----------
constexpr uint64_t CENTER_FREQ_HZ = CFG_CENTER_FREQ_HZ;
constexpr int TX_RANDOM_OFFSET_HZ = CFG_TX_RANDOM_OFFSET_HZ;
constexpr int TX_EVERY_N_SLOTS = CFG_TX_EVERY_N_SLOTS;
constexpr const char *NTP_SERVER = CFG_NTP_SERVER;

// ---------- web interface ----------
constexpr const char *MDNS_NAME = CFG_MDNS_NAME;
constexpr bool WEB_CHECK_HOST = CFG_WEB_CHECK_HOST;

// ---------- console ----------
constexpr uint32_t SERIAL_BAUD = CFG_SERIAL_BAUD;
constexpr uint64_t STEP_HZ = CFG_STEP_HZ;
constexpr uint32_t TONE_DWELL_MS = CFG_TONE_DWELL_MS;
constexpr uint32_t LED_BLINK_MS = CFG_LED_BLINK_MS;

}  // namespace config
